### ISSUE TITLE
The application crashes when i click on Start Quiz multiple times

### ISSUE THREAD

**Issue by 44asad** [XiangRongLin/HowTheyWrite#10]
### Expected behavior:
I expected that the application should not be crash when i click on Start Quiz.

### Actual behavior:
After configure the application when i click on start Quiz option,the application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app
2.Open the application.
3.Then click on any other Lessons.
4.click on start quiz.
5.Note the Bug.

### information
App version:v1.0.1
os:Android 8.1.0
Device: symphony i72
### Recording of the bug
 
https://youtu.be/Lx9y0rtXEy0

#### Logcat:
<Pre><code>07-21 14:17:21.905 18839 18839 E AndroidRuntime: FATAL EXCEPTION: main
07-21 14:17:21.905 18839 18839 E AndroidRuntime: Process: com.kaiserpudding.howtheywrite, PID: 18839
07-21 14:17:21.905 18839 18839 E AndroidRuntime: java.lang.IllegalArgumentException: navigation destination com.kaiserpudding.howtheywrite:id/action_characterList_to_characterDetail is unknown to this NavController
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at androidx.navigation.NavController.navigate(NavController.java:816)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at androidx.navigation.NavController.navigate(NavController.java:757)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at androidx.navigation.NavController.navigate(NavController.java:743)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at androidx.navigation.NavController.navigate(NavController.java:875)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.kaiserpudding.howtheywrite.main.MainActivity.onCharacterListItemInteraction(MainActivity.kt:99)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.kaiserpudding.howtheywrite.characterList.CharacterListFragment.onListInteraction(CharacterListFragment.kt:113)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.kaiserpudding.howtheywrite.shared.multiSelect.MultiSelectFragment.onMultiSelectAdapterInteraction(MultiSelectFragment.kt:86)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.kaiserpudding.howtheywrite.shared.multiSelect.MultiSelectAdapter$MultiSelectViewHolder$1.onClick(MultiSelectAdapter.kt:93)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.view.View.performClick(View.java:6319)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.view.View$PerformClick.run(View.java:24837)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:790)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:99)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:164)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:6747)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
07-21 14:17:21.905 18839 18839 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)</code></pre>

**Comment by XiangRongLin** [comment]
I'll look into it.
Is your phone perhaps a bit slow?  I just testet it on a slow emulator, and the app will crash if you click on toQuiz before it finished loading the characters. Can you check if it still crashes if you wait for it to finish loading.
I have a different error message.
Yours indicates that you clicked on one of the characters to go to the detail screen. Can you check if it always is that message?

**Comment by XiangRongLin** [comment]
Ok, I found the cause of this problem.
It is causes by multiple clicks on the button, which causes the navController to run the navigation a second time.
For now it can be avoided by only single clicking until i find a solution for all buttons that i have.

**Comment by 44asad** [comment]
ok
