### ISSUE TITLE
(BUG HowTheyWrite v1.0  ) the Application crashes when i try to open the application 

### ISSUE THREAD

**Issue by friendsmobile** [XiangRongLin/HowTheyWrite#8]
# Project Information

* Repository:  https://github.com/XiangRongLin/HowTheyWrite 
* Project Name: HowTheyWrite
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/XiangRongLin/HowTheyWrite/releases

# Expected behavior

when I try to open the application all option should appear and the application should not be crash 

# Actual behavior

 the Application crashes when i try to open the application 

#### How to reproduce

* [Download ](https://github.com/XiangRongLin/HowTheyWrite/releases)the application
*  try to open the application
* Note the Error

* Browser/App version:  v1.0
* Operating system: 6.0

#### Recording Of The Bug

![20190720_153101](https://user-images.githubusercontent.com/51118734/61577648-3196d000-aa9f-11e9-9081-8db33e64b6a1.gif)

#### Logcat

<pre><code>D/AndroidRuntime(19113): Shutting down VM

E/AndroidRuntime(19113): FATAL EXCEPTION: main

E/AndroidRuntime(19113): Process: com.kaiserpudding.howtheywrite, PID: 19113

E/AndroidRuntime(19113): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kaiserpudding.howtheywrite/com.kaiserpudding.howtheywrite.main.MainActivity}: android.view.InflateException: Binary XML file line #27: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView

E/AndroidRuntime(19113): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

E/AndroidRuntime(19113): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime(19113): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime(19113): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime(19113): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(19113): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(19113): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(19113): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(19113): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(19113): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(19113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(19113): Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(19113): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:537)

E/AndroidRuntime(19113): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)

E/AndroidRuntime(19113): 	at com.kaiserpudding.howtheywrite.main.MainActivity.onCreate(MainActivity.kt:45)

E/AndroidRuntime(19113): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime(19113): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime(19113): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

E/AndroidRuntime(19113): 	... 10 more

E/AndroidRuntime(19113): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(19113): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(19113): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(19113): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(19113): 	... 21 more

E/AndroidRuntime(19113): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070071

E/AndroidRuntime(19113): 	at android.content.res.Resources.getValue(Resources.java:1542)

E/AndroidRuntime(19113): 	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:252)

E/AndroidRuntime(19113): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)

E/AndroidRuntime(19113): 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)

E/AndroidRuntime(19113): 	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)

E/AndroidRuntime(19113): 	at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationItemView.initialize(BottomNavigationItemView.java:107)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:525)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:302)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:214)

E/AndroidRuntime(19113): 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:124)

E/AndroidRuntime(19113): 	... 24 more
</code></pre>

**Comment by XiangRongLin** [comment]
I'll look into it. My first guess is that Android 6.0 may be the problem, since i only ever used it on my own Android 7.0 device.
I may just remove that part for now, since it serves no real purpose.

**Comment by friendsmobile** [comment]
I don.t  know what is a problem I am not a programer maybe a problem with devices or Application  you know better

**Comment by XiangRongLin** [comment]
The problem should be fixed now. Try the 1.0.1 release.

**Comment by friendsmobile** [comment]
thanx you
